// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use same Supabase project as external auth, with fallback for packaged builds
const FALLBACK_SUPABASE_URL = 'https://einpdmanlpadqyqnvccb.supabase.co';
const FALLBACK_SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpbnBkbWFubHBhZHF5cW52Y2NiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUxMjU4OTYsImV4cCI6MjA4MDcwMTg5Nn0.3D-GgnpM-jf8-mUSRqcjFK6QP_OOXWaANtozQqalszA';

const envSupabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const envSupabaseKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const SUPABASE_URL = envSupabaseUrl?.includes('einpdmanlpadqyqnvccb')
  ? envSupabaseUrl
  : FALLBACK_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = envSupabaseKey?.startsWith('eyJhbGciOiJIUzI1Ni')
  ? envSupabaseKey
  : FALLBACK_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});